on:
  push:
    branches:
      - main
    #branches-ignore:
    #  - "**"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        python_version: ["3.7"]

    steps:
      #- uses: actions/checkout@v3
      #  with:
      #    submodules: true

      - name: Clone GitHub repository
        run: |
          git clone --recurse-submodules https://github.com/openPupil/PyPupilEXT

      - name: Install system packages (macOS)
        run: |
          brew install gcc
          brew install ninja
          brew install nasm
          brew install gmp
          brew install cmake
          brew reinstall libomp
          brew install libmpc
          brew install wget
          brew install pkg-config
          which brew
          brew info libomp
          ls -l /usr/local/Cellar/
          ls -l /usr/local/Cellar/libomp/

      #- name: Get latest Cmake and ninja (All-Systems)
      #  uses: lukka/get-cmake@latest

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Restore artifacts, or setup vcpkg (All-Systems)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/PyPupilEXT/3rdparty/vcpkg"
          vcpkgJsonGlob: "**/vcpkg.json"
          runVcpkgInstall: false
          vcpkgGitCommitId: "e99d9a4facea9d7e15a91212364d7a12762b7512"

      - name: Install python build requirements (All-Systems)
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install numpy
          python -m pip install setuptools
          python -m pip install ninja
          python -m pip install cmake

      - name: Build wheels for Python ${{ matrix.python_version }} in ${{ runner.os }} (All-Systems)
        run: |
          cd PyPupilEXT
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
