on:
  push:
    branches:
      - main
    #branches-ignore:
    #  - "**"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-10.15]
        python_version: ["3.7"]

    steps:
      #- uses: actions/checkout@v3
      #  with:
      #    submodules: "recursive"

      - name: Clone GitHub repository
        run: |
          git clone https://github.com/openPupil/PyPupilEXT
          pwd
          cd PyPupilEXT
          ls -l

      - name: Get latest Cmake and ninja
        uses: lukka/get-cmake@latest

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: "${{ github.workspace }}/PyPupilEXT/3rdparty/vcpkg"
          vcpkgJsonGlob: "**/vcpkg.json"
          runVcpkgInstall: false

      - name: Get files in current directory
        run: |
          cd PyPupilEXT
          ls -l
          which cmake
          cmake --version
          python --version

      - name: Install build requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel
          python -m pip install numpy
          python -m pip install setuptools
          python -m pip install ninja
          python -m pip install cmake

      - name: Build wheels for Python ${{ matrix.python_version }} in ${{ runner.os }}
        run: |
          cd PyPupilEXT
          python setup.py bdist_wheel

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
